# Generated by Django 4.0.1 on 2022-01-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=200)),
                ('User_Name', models.CharField(max_length=200)),
                ('User_Password', models.CharField(max_length=200)),
                ('User_Info', models.CharField(max_length=200)),
                ('User_CreateDT', models.DateTimeField(verbose_name='date create')),
                ('User_RecentDT', models.DateTimeField(verbose_name='date recent')),
            ],
        ),
    ]
