# Generated by Django 4.0.1 on 2022-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_user_email_user_user_focus_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dashboard_Total_News_Count', models.CharField(max_length=200)),
                ('Dashboard_Total_Analysis_Count', models.CharField(max_length=200)),
                ('Dashboard_Total_Analysis_Rate', models.CharField(max_length=200)),
                ('Dashboard_Today_count', models.CharField(max_length=200)),
                ('Dashboard_CreateDT', models.DateTimeField(verbose_name='date create')),
            ],
        ),
    ]
