# Generated by Django 4.0.1 on 2022-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noticeboard_Title', models.CharField(max_length=200)),
                ('Noticeboard_Content', models.CharField(max_length=200)),
                ('Noticeboard_Type', models.CharField(max_length=200)),
                ('Noticeboard_CreateDT', models.DateTimeField(verbose_name='date create')),
                ('Noticeboard_UpdateDT', models.DateTimeField(verbose_name='date recent')),
                ('Noticeboard_ETC01', models.CharField(blank=True, max_length=200)),
                ('Noticeboard_ETC02', models.CharField(blank=True, max_length=200)),
                ('Noticeboard_ETC03', models.CharField(blank=True, max_length=200)),
                ('Noticeboard_ETC04', models.CharField(blank=True, max_length=200)),
                ('Noticeboard_ETC05', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='Dashboard_ETC01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='Dashboard_ETC02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='Dashboard_ETC03',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='Dashboard_ETC04',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='Dashboard_ETC05',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='USER_ETC01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='USER_ETC02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='USER_ETC03',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='USER_ETC04',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='USER_ETC05',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
