# Generated by Django 4.0.1 on 2022-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_noticeboard_dashboard_dashboard_etc01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='Noticeboard_Content',
            field=models.TextField(blank=True),
        ),
    ]
