# Generated by Django 4.0.1 on 2022-02-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Analysis_Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_Analysis_Company', models.CharField(db_index=True, max_length=200)),
                ('News_Analysis_Title', models.CharField(db_index=True, max_length=200)),
                ('News_Analysis_From', models.CharField(db_index=True, max_length=200)),
                ('News_Morphs', models.CharField(max_length=200)),
                ('ETC1', models.TextField()),
                ('ETC2', models.TextField()),
                ('ETC3', models.TextField()),
                ('ETC4', models.TextField()),
                ('ETC5', models.TextField()),
                ('News_Analysis_CreateDT', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='News_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_Company_Code', models.CharField(max_length=200)),
                ('News_Company_Name', models.CharField(max_length=200)),
                ('ETC1', models.TextField()),
                ('ETC2', models.TextField()),
                ('ETC3', models.TextField()),
                ('ETC4', models.TextField()),
                ('ETC5', models.TextField()),
                ('News_Company_CreateDT', models.DateTimeField(verbose_name='date created')),
                ('News_Company_UpdateDT', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='News_company',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='News_from',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='News_title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
