# Generated by Django 4.0.1 on 2022-02-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0002_news_analysis_raw_news_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analysis_raw',
            name='ETC1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analysis_raw',
            name='ETC2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analysis_raw',
            name='ETC3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analysis_raw',
            name='ETC4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analysis_raw',
            name='ETC5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_company',
            name='ETC1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_company',
            name='ETC2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_company',
            name='ETC3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_company',
            name='ETC4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_company',
            name='ETC5',
            field=models.TextField(blank=True),
        ),
    ]
