# Generated by Django 4.0.1 on 2022-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0004_alter_news_analysis_raw_news_morphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ETC1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ETC2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ETC3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ETC4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ETC5',
            field=models.TextField(blank=True),
        ),
    ]
