# Generated by Django 4.0.1 on 2022-04-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0008_bs4_news_news_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bs4_news_company_crawl',
            name='TYPE_TOOLS1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bs4_news_company_crawl',
            name='TYPE_TOOLS2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bs4_news_company_crawl',
            name='TYPE_TOOLS3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bs4_news_company_crawl',
            name='TYPE_TOOLS4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bs4_news_company_crawl',
            name='TYPE_TOOLS5',
            field=models.TextField(blank=True),
        ),
    ]
