# Generated by Django 4.0.1 on 2022-04-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0009_bs4_news_company_crawl_type_tools1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BS4_NEWS_ANALYSIS_WORD_EXCLUDED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_CODE', models.CharField(db_index=True, max_length=200)),
                ('EXCLUDED_WORD', models.TextField(blank=True)),
                ('DESCRIPTION_INFO', models.TextField(blank=True)),
                ('UPDATE_DATETIME', models.DateTimeField(verbose_name='date updated')),
                ('UPDATE_USER', models.CharField(db_index=True, max_length=200)),
                ('CREATE_DATETIME', models.DateTimeField(verbose_name='date created')),
                ('CREATE_USER', models.CharField(db_index=True, max_length=200)),
                ('ETC1', models.TextField(blank=True)),
                ('ETC2', models.TextField(blank=True)),
                ('ETC3', models.TextField(blank=True)),
                ('ETC4', models.TextField(blank=True)),
                ('ETC5', models.TextField(blank=True)),
            ],
        ),
    ]
