# Generated by Django 4.0.1 on 2022-05-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0010_bs4_news_analysis_word_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='BS4_NEWS_COMPANY_CRAWL_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_CODE', models.CharField(db_index=True, max_length=200)),
                ('DOMAIN_URL', models.TextField(blank=True)),
                ('DOMAIN_QUERY_STRING', models.TextField(blank=True)),
                ('TARGET_CRAWL_URL', models.TextField(db_index=True, max_length=1000)),
                ('UPDATE_DATETIME', models.DateTimeField(verbose_name='date updated')),
                ('UPDATE_USER', models.CharField(db_index=True, max_length=200)),
                ('CREATE_DATETIME', models.DateTimeField(verbose_name='date created')),
                ('CREATE_USER', models.CharField(db_index=True, max_length=200)),
                ('DESCRIPTION_INFO', models.TextField(blank=True)),
                ('ETC1', models.TextField(blank=True)),
                ('ETC2', models.TextField(blank=True)),
                ('ETC3', models.TextField(blank=True)),
                ('ETC4', models.TextField(blank=True)),
                ('ETC5', models.TextField(blank=True)),
            ],
        ),
    ]
