# Generated by Django 4.0.1 on 2022-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0011_bs4_news_company_crawl_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs4_news_company_crawl_data',
            name='TARGET_CRAWL_URL',
            field=models.TextField(db_index=True, max_length=300),
        ),
    ]
