# Generated by Django 4.0.1 on 2022-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0015_alter_bs4_news_company_crawl_data_target_crawl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bs4_news_company_crawl_data',
            name='TARGET_RAW_HTML_DATA',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bs4_news_company_crawl_data',
            name='TARGET_CRAWL_URL',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
