# Generated by Django 4.0.1 on 2022-05-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs4news', '0018_bs4_news_company_scrap_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bs4_news_company_scrap',
            name='TARGET_CRAWL_URL',
        ),
    ]
